### ISSUE TITLE
[Bug] Web Client: HTTPS > HTTP After Logged in

### ISSUE THREAD

**Issue by NotHGM** [Ayymoss/BanHub#44]
**Issue it self**
Once being logged in for x amount of time, when re-opening the page you are greeted with `An unhandled error has occurred. Reload`.
After checking Console it shows its trying to redirect from HTTPS > HTTP, Only way to fix currently is to clear all site data and not log in.

**Screenshot of Console**
![Screenshot_1521](https://user-images.githubusercontent.com/102256497/221330573-b72cf438-6a80-4672-b372-a246a23633fc.png)

**Comment by Ayymoss** [comment]
This may be a caching issue since there are no references anywhere to that account endpoint.

HGM's been asked to clear the cache and attempt to replicate it.

**Comment by Ayymoss** [comment]
Maybe fixed? Idk. HGM can't replicate.
